<% require 'sha1' %>
---
# Hostname or IP address to bind to. 
:host: 0.0.0.0

# Port merb runs on or starting port for merb cluster.
:port: "4000"

# Uncomment if you have more than one ORM or if you need to be specific about
# which memory store to use. Built-in options are: memory, cookie, or mem_cache
:session_store: cookie

#:memory_session_ttl: 3600 # one hour

# A secret key is required when using the 'cookie' session store (default), 
# change this value to something unique to your application and keep it private
:session_secret_key: <%= SHA1.new(rand(100000000000).to_s).to_s %>
